### ISSUE TITLE
INVALID_CLIENT: Invalid redirect URI

### ISSUE THREAD

**Issue by MonochromeOS** [IamTiji/spotify-controller#1]
After inputting my ID and secret, I just get a blank page with the error message "INVALID_CLIENT: Invalid redirect URI." I suspect this is related to Spotify not accepting the redirect URL because it's "insecure." I had to add change the "http" to "https" for it to even accept the redirect URL.

![Image](https://github.com/user-attachments/assets/87052221-2153-432b-b2a6-24719df3850f)

![Image](https://github.com/user-attachments/assets/a026ce2a-1165-42e9-830c-94a6add30933)

**Comment by IamTiji** [comment]
Resolved in 2.1

**Comment by MonochromeOS** [comment]
Even with the updated redirect URL, this issue still occurs. I don't know if it's something on the mod's end or on Spotify's end, but I quite literally can't use the mod because it won't let me log in.

**Comment by IamTiji** [comment]
Try using 2.2. They changed api again. Sorry for late reply

**Comment by MonochromeOS** [comment]
Any plans for a 1.21.4 backport of 2.2 soon? I'd move over to 1.21.5, but my mods haven't updated yet.
